// NOTE:
// These implementations are incomplete. Options should not be modified.
//
#ifndef _ENABLE_DARK_MODE_TEST
#define _ENABLE_DARK_MODE_TEST              1
#endif

#ifndef _ENABLE_UAH
#define _ENABLE_UAH                         1
#endif

#ifndef _ENABLE_MULTI_LANGUAGE
#define _ENABLE_MULTI_LANGUAGE              0
#endif

#ifndef _ENABLE_OLE
#define _ENABLE_OLE                         0
#endif

#ifndef _ENABLE_TOOLS
#define _ENABLE_TOOLS                       0
#endif

#ifndef _ENABLE_FILE_MANAGER
#define _ENABLE_FILE_MANAGER                0
#endif

#ifndef _ENABLE_INTERNAL_COMMAND
#define _ENABLE_INTERNAL_COMMAND            0
#endif

#ifndef _ENABLE_ROOTDIRECTORY_LIST
#define _ENABLE_ROOTDIRECTORY_LIST          0
#endif

#ifndef _ENABLE_FILES_USE_SHELL_ICON
#define _ENABLE_FILES_USE_SHELL_ICON        0
#endif

#ifndef _ENABLE_FILELIST_SINGLETON
#define _ENABLE_FILELIST_SINGLETON          1
#endif

