#ifndef _DEF_VOLUME_CONSOLE_DEF
#define _DEF_VOLUME_CONSOLE_DEF

typedef struct _CONSOLE_VIEW_ID {
	UINT wndId;
	GUID wndGuid;
} CONSOLE_VIEW_ID; 

#define _PROP_CONSOLE_VIEW_ID L"ConsoleViewId"

#ifdef __cplusplus
inline CONSOLE_VIEW_ID *_GET_CONSOLE_VIEW_ID(HWND hwndView)
{
	return (CONSOLE_VIEW_ID *)GetProp(hwndView,_PROP_CONSOLE_VIEW_ID);
}
#else
#define _GET_CONSOLE_VIEW_ID(hwndView) ((CONSOLE_VIEW_ID *)GetProp(hwndView,_PROP_CONSOLE_VIEW_ID))
#endif

#ifndef _VOLUME_CONSOLE_CREATE_PARAM
#define _VOLUME_CONSOLE_CREATE_PARAM
typedef struct _VOLUME_CONSOLE_CREATE_PARAM
{
	DWORD dwFlags;
	PWSTR pszInitialDeviceName;
	PAGE_CONTEXT *Context;
} VOLUME_CONSOLE_CREATE_PARAM,*PVOLUME_CONSOLE_CREATE_PARAM;
#endif

#ifndef VOLUME_DLL_FLAG_ENABLE_DARK_MODE
#define VOLUME_DLL_FLAG_ENABLE_DARK_MODE 0x1
#endif

#define VOLFILES_FLG_USE_SHELL_ICON               0x1000
#define VOLFILES_FLG_USE_PROXY_OPEN               0x8000

#define VOLDISKS_FLG_USE_SHELL_ICON                0x1000
#define VOLDISKS_FLG_USE_PROXY_OPEN                0x8000
#define VOLDISKS_FLG_NO_OPEN_VOLUME_FILE_EXPLORER  0x0800


#endif
