#pragma once

enum {
	VOLUME_CONSOLE_NONE=0,
	VOLUME_CONSOLE_HOME,
	VOLUME_CONSOLE_VOLUMELIST,
	VOLUME_CONSOLE_PHYSICALDRIVELIST,
	VOLUME_CONSOLE_SHADOWCOPYLIST,
	VOLUME_CONSOLE_STORAGEDEVICE,
	VOLUME_CONSOLE_MOUNTEDDEVICE,
	VOLUME_CONSOLE_DOSDRIVELIST,
	VOLUME_CONSOLE_VOLUMEINFORMAION,
	VOLUME_CONSOLE_PHYSICALDRIVEINFORMAION,
	VOLUME_CONSOLE_DISKLAYOUT,
	VOLUME_CONSOLE_MAX_ID,
};

//
// Folder tree item ident
//

#define	MAX_PAGE_TYPE VOLUME_CONSOLE_MAX_ID


typedef struct _VOLUME_CONSOLE_CREATE_PARAM
{
	PWSTR pszReserved;
} VOLUME_CONSOLE_CREATE_PARAM,*PVOLUME_CONSOLE_CREATE_PARAM;

EXTERN_C
HWND
WINAPI
CreateVolumeConsoleWindow(
	HWND hwnd,
	UINT ConsoleType,
	PVOLUME_CONSOLE_CREATE_PARAM pParam
	);
